### ISSUE TITLE
SOIL uses const char* instead of const wchar_t*

### ISSUE THREAD

**Issue by Andy608** [kbranigan/Simple-OpenGL-Image-Library#14]
SOIL only supports narrow strings when loading images, but it should accept wide strings to allow for filenames with different characters than just English. Thanks.

**Comment by njcrawford** [comment]
I'm not kbranigan, but I have used SOIL a lot in the past.

SOIL_load_image() is basically a pass-through to stbi_load(). See here for definition: https://github.com/kbranigan/Simple-OpenGL-Image-Library/blob/master/src/SOIL.c#L1433

As far as I can tell, the latest version of stbi_load() still uses char const *, so there's not much SOIL can do short of writing a new image loader. See the function definition here: https://github.com/nothings/stb/blob/master/stb_image.h#L1145

**Comment by Andy608** [comment]
Thanks for the reply njcrawford. I ended up creating a function that converts my wstring to a regular string and then converted the string to a const char* using string.c_str(); (i had this issue because i am using window's CreateDirectory function for my filepath and that returns a wstring). Thanks again,
- Andy608
